output_A = int("52")
output_B = float("52.235")
print(type(output_A),output_A)
print(type(output_B),output_B)

intput_a = float(input("첫번째 수 : "))
intput_b = int(input("두번째 수 : "))

print("덧셈결과 : ", intput_a + intput_b)
print("뺄셈결과 : ", intput_a - intput_b)
print("곱셈결과 : ", intput_a * intput_b)
print("나누기결과 : ", intput_a / intput_b)

Str_input = input("원의 반지름 입력 :")
num_input = float(Str_input)
print()
print("반지름 : ", num_input)
print("둘레 :", 2 * 3.14 * num_input)
print("넓이 : ", 3.14 * num_input**2)

String_AA = input("문자열 입력 : ")
String_BB = input("문자열 입력 : ")
print(String_AA + String_BB)
print(String_BB+String_AA)
print("기초부터 잡아보자 :)")